title: My Quran Audio Site
description: A simple Quran audio player using Jekyll and GitHub Pages
author: Your Name
email: example@example.com
baseurl: "" # Leave this blank if using a custom domain
url: "https://yourusername.github.io" # Change this if using a custom domain

# Use a built-in GitHub Pages theme
theme: minima

# Optional settings
markdown: kramdown
plugins:
  - jekyll-feed
